// Placeholder resource list. In a real deployment this should be localized by
// the user's region (IP/locale, or an explicit "where are you" onboarding
// step) rather than defaulting to US numbers for everyone.
export const CRISIS_RESOURCES = [
  { label: "988 Suicide & Crisis Lifeline (US)", detail: "Call or text 988 — free, 24/7" },
  { label: "Crisis Text Line", detail: "Text HOME to 741741" },
  { label: "Outside the US", detail: "findahelpline.com lists local crisis lines by country" },
  { label: "Immediate danger", detail: "Contact your local emergency number (e.g. 911 in the US) right now" },
];

// This message is a fixed template, NOT generated by the chat LLM. That's a
// deliberate safety choice: the model should never be improvising in this
// moment, and the response must not depend on the model behaving well that
// turn. See README "Crisis & Safety Handling" for the rationale.
export function buildCrisisMessage() {
  const resourceLines = CRISIS_RESOURCES.map((r) => `• ${r.label} — ${r.detail}`).join("\n");
  return (
    "I'm really glad you told me this. I want to be honest with you: I'm an AI, and " +
    "when things feel this heavy or dangerous, I'm not the right one to handle it alone — " +
    "you deserve support from people who are trained for this and can actually help.\n\n" +
    "Here's how to reach someone right now:\n" +
    resourceLines +
    "\n\nYou don't have to carry this by yourself. Is there someone nearby — a friend, " +
    "family member, or doctor — you could reach out to right now?"
  );
}
